apiVersion: v1
kind: Service
metadata:
  name: mattermost-postgres
  namespace: mattermost
spec:
  selector:
    app: mattermost-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
